
@host=http://localhost:5080

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "email": "john@smith.com",
    "password": "test123"
}